import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DarkModeToggle } from "./components/DarkModeToggle";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased h-screen w-full`}>
        <Providers>
          <div className="dark:bg-zinc-800 light:bg-slate-100 h-full w-full relative flex flex-col">
            <div className="flex justify-end px-6 py-4">
              <DarkModeToggle />
            </div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
